# Generated by Django 4.2 on 2023-04-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_ratings_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
