# Generated by Django 4.2 on 2023-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='current_rating',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=0),
        ),
    ]
