# Generated by Django 4.2 on 2023-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_pizza_current_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='current_rating',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
    ]
