# Generated by Django 4.2 on 2023-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_rename_title_rating_pizza_to_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('submissions', models.FileField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
