# Generated by Django 4.2 on 2023-04-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_submissions_alter_pizza_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submissions',
            new_name='submission',
        ),
    ]
